### ISSUE TITLE
Suggestion: postgres version bump to 11

### ISSUE THREAD

**Issue by florianm** [opendatakit/central#108]
I'm using a hosted postgres 11.5 instance, and since ODK Central uses [postgres 9](https://github.com/opendatakit/central/blob/master/docker-compose.yml#L4), my backups fail with 

```
{"stack":"Error: Command failed: pg_dump -j 4 -F d -f /tmp/tmp-8047tMOTtqAWLAG -h XXX.postgres.database.azure.com -U XXX odk_prod\npg_dump: server version: 11.5; pg_dump version: 9.6.15\npg_dump: aborting because of server version mismatch\n\n at ChildProcess.exithandler (child_process.js:297:12)\n at ChildProcess.emit (events.js:203:13)\n at maybeClose (internal/child_process.js:1021:16)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)","message":"Command failed: pg_dump -j 4 -F d -f /tmp/tmp-8047tMOTtqAWLAG -h XXX.postgres.database.azure.com -U XXX odk_prod\n pg_dump: server version: 11.5; pg_dump version: 9.6.15\npg_dump: aborting because of server version mismatch\n","success":false}
```
With the important bits being `server version: 11.5; pg_dump version: 9.6.15`.

Could we bump postgres to v11?

**Comment by issa-tseng** [comment]
if you can figure out the appropriate procedure to migrate existing docker-compose installations to postgres 11+ without asking anybody to do brain surgery, i would be quite happy to upgrade postgres.

**Comment by florianm** [comment]
This process probably should happen with each major postgres release so Central won't fall too far behind, right?

E.g. this https://jlelse.blog/dev/migrate-postgres-docker/ but as an "upgrade once" script in the same vein as "wait_for_it.sh"?

**Comment by issa-tseng** [comment]
postgres are very very very good at maintaining long-term support for old versions, so while in general yes it would be ideal to keep up with the fancy nice new features in 10/11.x i'm not too concerned about being on 9.x. there are plenty of major installs that can't move beyond 8.x.

something like that script, yes, but:

1. it would probably be really dangerous to just run that automatically without eg encouraging the user to create a backup first.
2. the problem you're going to run into is that the procedure given in that post (which looks similar to what i've seen before) involves a lot of meta-level wrangling at the docker level, which won't containerize very well.

**Comment by florianm** [comment]
Central doesn't do anything super fancy that will be dropped by postgres anytime soon, right? 
In that case I'm closing this feature request issue.
