### ISSUE TITLE
decrypted attachments have a .enc extension

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/central#114]
Project was encrypted after 2 submissions. And 2 more submissions after encryption was turned on.
<img width="415" alt="Screen Shot 2019-11-12 at 9 15 35 PM" src="https://user-images.githubusercontent.com/4806884/68727197-b9926f80-0591-11ea-98aa-b4f956b513b6.png">
CSV shows all the data rows.
<img width="227" alt="Screen Shot 2019-11-12 at 9 15 21 PM" src="https://user-images.githubusercontent.com/4806884/68727211-c020e700-0591-11ea-91bf-8aad7a189644.png">
But the two images are downloading as encrypted still.
<img width="244" alt="Screen Shot 2019-11-12 at 9 15 47 PM" src="https://user-images.githubusercontent.com/4806884/68727205-bc8d6000-0591-11ea-8311-f8d69b9cdb61.png">

**Comment by issa-tseng** [comment]
and this was with managed encryption?

**Comment by danbjoseph** [comment]
It was through this interface.
<img width="451" alt="Screen Shot 2019-11-14 at 8 55 32 PM" src="https://user-images.githubusercontent.com/4806884/68910830-28520300-0721-11ea-8143-0c4508c77fe4.png">

I will try and replicate. We had more people testing the server at once than may have been appropriate for the size of the EC2 instance.

**Comment by issa-tseng** [comment]
server load cannot matter; something else is weird here. somehow it doesn't realize that it ought to decrypt those attachments. does the row data itself decrypt correctly?

**Comment by danbjoseph** [comment]
sent 2 more test submissions

![Screen Shot 2019-11-16 at 1 27 33 PM](https://user-images.githubusercontent.com/4806884/68997479-e934c680-0874-11ea-8351-92d08480b0f4.png)

all rows show data in the csv file

![Screen Shot 2019-11-16 at 1 27 27 PM](https://user-images.githubusercontent.com/4806884/68997478-e8039980-0874-11ea-829a-903eeb0fc1ce.png)

media still shows with `.enc` extension

![Screen Shot 2019-11-16 at 1 27 44 PM](https://user-images.githubusercontent.com/4806884/68997492-32851600-0875-11ea-934d-d77d9d3501bc.png)

however! i tried removing the `.enc` extension and... the images aren't actually encrypted.

![Screen Shot 2019-11-16 at 1 29 53 PM](https://user-images.githubusercontent.com/4806884/68997498-52b4d500-0875-11ea-95d7-0fdf6b1167b2.png)

happy to give you access to the instance and/or the server (an Amazon EC2 instance) if you'd like to poke around.

**Comment by issa-tseng** [comment]
ohhhhhhhhhh true!!

i don't mess with the filename at all when i decrypt it. so they'll all always have `.enc` if that's how they were given to me. the spec doesn't say anything about the filenames being munged or what to do with them on export.

@lognaturel should i always detect `.enc` and strip it on export?

**Comment by lognaturel** [comment]
> the spec doesn't say anything about the filenames being munged or what to do with them on export.

🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️ Filed spec issue at https://github.com/opendatakit/xforms-spec/issues/255

> @lognaturel should i always detect .enc and strip it on export?

Yes, please.
