### ISSUE TITLE
issue with CSV for pulldata

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/central#115]
Created a test form that uses pulldata in a calculate to bring in values from an external csv.
[pulldata.xlsx](https://github.com/opendatakit/central/files/3849441/pulldata.xlsx) & [registered.csv.zip](https://github.com/opendatakit/central/files/3849446/registered.csv.zip) (not real data)

Converted via https://opendatakit.org/xlsform/ to [pulldata.xml.zip](https://github.com/opendatakit/central/files/3849444/pulldata.xml.zip)

Works as expected on https://sandbox.aggregate.opendatakit.org/

![Screenshot_20191114-202400](https://user-images.githubusercontent.com/4806884/68910551-2c315580-0720-11ea-83a2-a3581f85f085.png)![Screenshot_20191114-202406](https://user-images.githubusercontent.com/4806884/68910553-2dfb1900-0720-11ea-8662-741338eddc40.png)

Uploading to Central (installed in the last week), the site then asks me for an `RC.csv` file.

<img width="570" alt="Screen Shot 2019-11-14 at 8 26 06 PM" src="https://user-images.githubusercontent.com/4806884/68910628-816d6700-0720-11ea-828b-f7c8b1afb47b.png">

I try to upload the `registered.csv` file but get an error. 

<img width="393" alt="Screen Shot 2019-11-14 at 8 26 20 PM" src="https://user-images.githubusercontent.com/4806884/68910683-a2ce5300-0720-11ea-97ea-9f9b3bf253a8.png">

I try renaming the csv to `RC.csv` and it uploads but the form doesn't work as expected.

![Screenshot_20191114-203441](https://user-images.githubusercontent.com/4806884/68910709-b5e12300-0720-11ea-8dd6-8632c286e50a.png)

**Comment by lognaturel** [comment]
This is actually looking like a pyxform issue. I can't understand where it's pulling `RC.csv` from and this will require deeper investigation. Central is doing exactly what it should be given the form XML given to it. [pulldata.xml.zip](https://github.com/opendatakit/central/files/3849736/pulldata.xml.zip) is what it should be producing.

**Comment by danbjoseph** [comment]
should i log this issue at https://github.com/XLSForm/pyxform/issues?
can you move the issue over there?

**Comment by lognaturel** [comment]
Ooh, looks like I can only move things within the `opendatakit` org unfortunately. Why don't I do a little digging to close in on where the issue is happening and I can file based on that. In the mean time, @issa-tseng can take a quick look and see if I'm missing anything that might point to a Central issue. I'm pretty confident not but it's worth a check.

**Comment by issa-tseng** [comment]
yeah, this looks like a conversion issue. i guess maybe however the convertor is parsing the pulldata expression it sees the `"RC"` and treats it with greater precedence than `'registered'` even though the latter comes first?
