### ISSUE TITLE
SSL_TYPE=letsencrypt  error

### ISSUE THREAD

**Issue by ddiaz2380** [opendatakit/central#116]
When I use letsencrypt, the nginx always falls and is unhealthy, I change the nano .env to custom and it works but without ssl authentication so I cannot download the forms from the devices. Any solution? please help. Sorry for my English is very bad!

Couldn't find keyfile /etc/letsencrypt/live/xxxx.com/privkey.pem for /etc/nginx/conf.d/odk.conf.nokey

**Comment by issa-tseng** [comment]
your english is fine. :)

in general, this question should be asked on forum.opendatakit.org, not here.

but, can you try this:
1. restart the server
2. after a minute or two, run `docker-compose logs nginx`

it should output some logging explaining why the letsencrypt verification is failing.

**Comment by ddiaz2380** [comment]
Apparently the problem is with the certificates, I generated them manually
but I don't know how to put them inside the docker. When I select the self
option in SSL_TYPE, it allows me to execute centrally correctly but without
https, what causes me to not be able to download the forms from the devices.

**Comment by issa-tseng** [comment]
oh! so you don't want letsencrypt _or_ selfsign, then.

you want to follow the instructions here: https://docs.opendatakit.org/central-install-digital-ocean/#using-a-custom-ssl-certificate
which uses `customssl`.

**Comment by ddiaz2380** [comment]
Yes, if I want to sign with letsencrypt. But I have the mistakes I pointed
out.
I could only run the plant with the self option without a certificate,
having it like this does not allow me to download forms. If I want to have
letsencrypt but I get an error installing it and the control panel goes down

**Comment by ddiaz2380** [comment]
https://odk.siemprosalta.ml/#/

Now it is running perfect Central, but without https letsencrypt this does
not let me download forms from the mobile. When I set SSL_TYPE =
letsencrypt central it gets unhealthy

**Comment by issa-tseng** [comment]
can you do this, then?

> but, can you try this:
> 
> 1. restart the server
> 2. after a minute or two, run `docker-compose logs nginx`

**Comment by ddiaz2380** [comment]
restart server and run it
docker-compose logs nginx | less

**Comment by issa-tseng** [comment]
closing this ticket in favor of the forum thread..
