### ISSUE TITLE
Form Access State is not inheriting state when you upload the new version

### ISSUE THREAD

**Issue by OdiljonQurbon** [opendatakit/central#122]
I noticed that when I delete the existing form from the Collect and upload the new version with the same Form ID, Form state in the Form Access page shows that my App Users still have an access. But when trying to download the Form from ODK Collect it appears that they don't have an access. It is only works when:
1. **Deselecting** access and click **Save** button
2. **Selecting** again and click **Save** button

![FormAccessBug](https://user-images.githubusercontent.com/54809428/71878689-4e05f200-313d-11ea-9ffa-2da15dacdbcb.png)

It would be great if every versions of the same form could inherit form access for app users.

**Comment by issa-tseng** [comment]
thanks for the report! i'll take a look tomorrow and let you know what i find.
in the meanwhile, is this more of an annoyance or more of a major issue for you?

**Comment by OdiljonQurbon** [comment]
It's not a major issue, just making a confusion.

**Comment by issa-tseng** [comment]
oh okay. i have read this again (sorry, i was tired and sleepy when i first tried), and i think the [next release of central](https://docs.google.com/document/d/1_Vv6Rhmh9ZYpKHzMSrPSPZJQAJn6NXvWZKpAEpvFkbI/edit#heading=h.26jkdbfha262) will solve this for you incidentally.

**Comment by issa-tseng** [comment]
i'm going to close this for now, but please feel free to reopen or resubmit if you feel i've got the wrong read here.
