### ISSUE TITLE
ACMEv1 needs to be upgraded to ACMEv2 by June 1?

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/central#125]
Not sure if this is due to something I did or with the software. Probably either already fixed or on your radar if the software. I received an email from noreply @ letsencrypt.org

> According to our records, the software client you're using to get Let's
> Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
> in the past two weeks using the ACMEv1 protocol. Your client's IP address was:
> 
>  xx.xx.xx.xx
> 
> Beginning June 1, 2020, we will stop allowing new domains to validate using
> the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
> then, or certificate issuance will fail. For most people, simply upgrading to
> the latest version of your existing client will suffice. You can view the
> client list at: https://letsencrypt.org/docs/client-options/

The IP address is for my Central installation.

Searching I saw "ACMEv1" mentioned in #120.

I'm running Central:
```
versions:
261b542ec4372a73864a3babdc2ef9e86eff513d
 4dc05d9dbdac3778dd7c1f3ed18dc26d99723b8b client (v0.7.0)
 1c64bb8a4bc5d2312302e57508997102208d030a server (v0.7.0)
```

**Comment by issa-tseng** [comment]
hmmm i believe we fixed this issue [here](https://github.com/opendatakit/central/pull/121). perhaps try running a [full update](https://docs.opendatakit.org/central-upgrade/) on Central and restart everything?

**Comment by danbjoseph** [comment]
will revisit if i get another notification or something breaks. thank you.
