### ISSUE TITLE
renewal of expiring SSL cert with Let's Encrypt?

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/central#126]
Two users on the forum have posted about expiring certificates:
- https://forum.opendatakit.org/t/renew-ssl-certificate/25186
- https://forum.opendatakit.org/t/let-s-encrypt-certificate-renewal/25514

I just received an email about it:
```
Hello,

Your certificate (or certificates) for the names listed below will expire in 20 days (on 07 Apr 20 13:44 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

We recommend renewing certificates automatically when they have a third of their
total lifetime left. For Let's Encrypt's current 90-day certificates, that means
renewing 30 days before expiration. See
https://letsencrypt.org/docs/integration-guide/ for details.

xxxxxxxxxxxxxxxxxx

For any questions or support, please visit https://community.letsencrypt.org/. Unfortunately, we can't provide support by email.

For details about when we send these emails, please visit https://letsencrypt.org/docs/expiration-emails/. In particular, note that this reminder email is still sent if you've obtained a slightly different certificate by adding or removing names. If you've replaced this certificate with a newer one that covers more or fewer names than the list above, you may be able to ignore this message.

If you are receiving this email in error, unsubscribe at xxxxxxxxxxxxxxxxxx

Regards,
The Let's Encrypt Team
```

Is there a user action that needs to be taken?

Is this just a mismatch between when Central renews its certificates and when Let's Encrypt sends notifications?

Possibly related: https://github.com/opendatakit/central/issues/125

**Comment by issa-tseng** [comment]
hmmm. shouldn't be. and i know you've updated for the new acme protocol since that was your ticket so something else must be going on here. i won't be around to investigate for another few days but perhaps @matthew-white could take a shot?

**Comment by yanokwa** [comment]
@danbjoseph Let's get your LetsEncrypt logs and see if there is anything useful there.
```
cd ~;
docker cp nginx:/var/log/letsencrypt/ /tmp/letsencrypt_logs;
tar -zcvf letsencrypt_logs.tar.gz /tmp/letsencrypt_logs;
```
That will put a letsencrypt_logs.tar.gz file in the home folder of your server. I'm not sure the logs are sensitive, so please email them to me directly.

It'd also be good to know your current version. You can get that at your.server.com/version.txt.

**Comment by danbjoseph** [comment]
🤦‍♂so... i had turned the EC2 instance off. which is probably why it hadn't renewed.
(i should've clarified at the start that my involvement in this issue was based on a sandbox deployment and seeing the other forum posts, and not something urgent based on a server being used in a project)

the last entry in the log is:
```
2020-01-25 16:15:41,349:INFO:certbot.renewal:Cert not yet due for renewal
2020-01-25 16:15:41,350:INFO:certbot.main:Keeping the existing certificate
```
/version.txt is:
```
versions:
261b542ec4372a73864a3babdc2ef9e86eff513d
 4dc05d9dbdac3778dd7c1f3ed18dc26d99723b8b client (v0.7.0)
 1c64bb8a4bc5d2312302e57508997102208d030a server (v0.7.0)
```

so my issue is user error. will have to see if the forum posters are able to reveal any issues w Central. i saw that one posted that they are running v0.5.0.

**Comment by issa-tseng** [comment]
okay. i bet the other 0.7 user hasn't applied that patch, and 0.5 surely will not have. i'll check in with them.

**Comment by dickoa** [comment]
Hi everyone,

Thanks for looking into this,  I also have the same error and using the same version (same version.txt), I'm sharing my log in case it helps.

```
2019-12-26 15:07:10,373:DEBUG:certbot._internal.main:certbot version: 1.0.0
2019-12-26 15:07:10,374:DEBUG:certbot._internal.main:Arguments: ['--cert-name', 'SERVER-NAME']
2019-12-26 15:07:10,374:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-12-26 15:07:10,391:DEBUG:certbot._internal.log:Root logging level set at 20
2019-12-26 15:07:10,391:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-12-26 15:07:10,392:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.0.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.8/site-packages/certbot/main.py", line 14, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1350, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1008, in delete
    cert_manager.delete(config)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/cert_manager.py", line 95, in delete
    storage.delete_files(config, certname)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/storage.py", line 319, in delete_files
    renewal_filename = renewal_file_for_certname(config, certname)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/storage.py", line 52, in renewal_file_for_certname
    raise errors.CertStorageError("No certificate found with name {0} (expected "
certbot.errors.CertStorageError: No certificate found with name SERVER-NAME (expected /etc/letsencrypt/renewal/SERVER-NAME.conf).

```

version.txt

```
versions:
261b542ec4372a73864a3babdc2ef9e86eff513d
 4dc05d9dbdac3778dd7c1f3ed18dc26d99723b8b client (v0.7.0)
 1c64bb8a4bc5d2312302e57508997102208d030a server (v0.7.0)
```

Thanks

**Comment by issa-tseng** [comment]
hi @dickoa: i have the same recommendation for you as the others: run the upgrade instructions for Central as found [here](https://docs.opendatakit.org/central-upgrade/). restart the server as instructed in that document. if the problem does not resolve after a couple of days, please let me know.
