### ISSUE TITLE
debian 8 installation failure: missing keys, broken packages when building service

### ISSUE THREAD

**Issue by arkhub** [opendatakit/central#37]
Steps that I've done to install in Debian 8 :
1. Install Docker (18.09) and Docker CE (version 1.23.2)
2. use non root user with access to sudo and docker without sudo
3. git clone the repo and use the command to update the dependencies
4. edit the .env files with appropriate settings
5. 
When executing `docker-compose build` on my vps there's a warning like this :
`Warning: apt-key output should not be parsed (stdout is not a terminal)
key 7FCC7D46ACCC4CF8:
2 signatures not checked due to missing keys
`
followed by errors that stopped the script :
`
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'service' failed to build: The command '/bin/sh -c echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" > /etc/apt/sources.list.d/pgdg.list;   wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc |   apt-key add -;   apt-get update; apt-get install -y cron gettext postgresql-client-9.6' returned a non-zero code: 100
`
is there something that I missed?

**Comment by clint-tseng** [comment]
my best guess is that while installing docker or docker-related things on the host system, something weird happened and apt couldn't actually resolve the system into a working state. is this a completely fresh debian system or do you use it for other things?

either way, perhaps [this answer](https://askubuntu.com/a/363244) will help.

**Comment by arkhub** [comment]
I finally made it run by modyfing the first few line in `service.dockerfile` into : 
```
### Custom yml
FROM node:carbon

WORKDIR /usr/odk

# workaround 01
RUN apt-get update; \
  apt-get install -y lsb-release apt-utils

# workaround for apt-key add warning
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
RUN apt-key adv --no-tty --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/pgdg.list; \
  apt-get update; apt-get install -y cron gettext postgresql-client-9.6
```

_(I use `lsb_release` from installed package previously because the os might be using debian 9 - stretch or other version.)_

there are few warnings after that but I don't know if that affect the system, after `docker-compose build` successful 
6. run `docker-compose create` (no errors so far)
7. run `cp files/docker-compose@.service /etc/systemd/system`
8. start the `systemctl start docker-compose@central` (no errors but no notifications or wait time either).
9. running `systemctl status docker-compose@central` resulted in : 
```● docker-compose@central.service - central via docker-compose
Loaded: loaded (/etc/systemd/system/docker-compose@.service; disabled)
Active: failed (Result: start-limit) since Thu 2018-12-27 12:29:25 UTC; 8h ago
Process: 4472 ExecStop=/usr/local/bin/docker-compose stop -v (code=exited, status=200/CHDIR)
Process: 4471 ExecStart=/usr/local/bin/docker-compose up (code=exited, status=200/CHDIR)
Main PID: 4471 (code=exited, status=200/CHDIR)`

Dec 27 12:29:24 <my hostname> systemd[1]: docker-compose@central.service: control process exited, code=exited status=200
Dec 27 12:29:24 <my hostname> systemd[1]: Unit docker-compose@central.service entered failed state.
Dec 27 12:29:25 <my hostname> systemd[1]: docker-compose@central.service holdoff time over, scheduling restart.
Dec 27 12:29:25 <my hostname> systemd[1]: Stopping central via docker-compose...
Dec 27 12:29:25 <my hostname> systemd[1]: Starting central via docker-compose...
Dec 27 12:29:25 <my hostname> systemd[1]: docker-compose@central.service start request repeated too quickly, refusing to start.
Dec 27 12:29:25 <my hostname> systemd[1]: Failed to start central via docker-compose.
Dec 27 12:29:25 <my hostname> systemd[1]: Unit docker-compose@central.service entered failed state.
```
10. strangely running `docker-compose up` result success and when I try `docker-compose ps` it shows services running : 
```
       Name                     Command                  State                        Ports
-------------------------------------------------------------------------------------------------------------
central_mail_1       /bin/entrypoint.sh exim -b ...   Up             25/tcp
central_nginx_1      /bin/bash /scripts/odk-set ...   Up (healthy)   0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
central_postgres_1   docker-entrypoint.sh postgres    Up             5432/tcp
central_service_1    ./wait-for-it.sh postgres: ...   Up             8383/tcp

```

And after that when I opened https://<my hostname> , it shows odk central up and running (can login after create the users, upload form and submit forms, there are problems with image upload but that's in other issues), is my step in installing odk central correct?

**Comment by arkhub** [comment]
ok, thanks.

**Comment by arkhub** [comment]
> my best guess is that while installing docker or docker-related things on the host system, something weird happened and apt couldn't actually resolve the system into a working state. is this a completely fresh debian system or do you use it for other things?
> 
> either way, perhaps [this answer](https://askubuntu.com/a/363244) will help.

sorry forgot to answer that, I installed it from "fresh system" provided by the vps provider, there are already apache and samba pre-installed in the vm so I removed them first. I try all 4 vm images available from the providers (ubuntu 16.04, ubuntu 18.04, debian 8 jessie, and debian 9 stretch). All of them give the same error results (warning 2 signatures missing keys followed by errors cannot install postgresql).

**Comment by clint-tseng** [comment]
hm, that's quite odd. which VPS provider is it?

**Comment by arkhub** [comment]
It's a local provider in my area called [https://www.niagahoster.co.id/](url)

**Comment by clint-tseng** [comment]
well, unfortunately i can't read their documentation, but i wonder if in the knowledgebase they maybe explain whether they have some kind of local apt mirror they use to lower latency times, and this is breaking the key chain?

**Comment by arkhub** [comment]
Unfortunately their F.A.Q also didn't explain much technical term. Currently I'm using Debian 8 Jessie in their vps server.

>but i wonder if in the knowledgebase they maybe explain whether they have some kind of local apt mirror they use to lower latency times, and this is breaking the key chain?

I don't know if they're using apt mirrors but here's what the sources.list looks like in the configuration :
```
deb http://ftp.debian.org/debian jessie main contrib non-free
deb http://ftp.debian.org/debian jessie-updates main contrib non-free
deb http://security.debian.org jessie/updates main contrib non-free
deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
```
As for the domain itself, it has been configured to use cloudflare for the caching but I don't think that will be a problem.

- The docker version that I've installed : 
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
side note : it's weird because I'm pretty sure I've installed docker 18.09 version (although it requires workaround because there's a bud that requires a workaround that I've found in linode forum) and after a while `apt update` shows an update for docker-ce.

- docker-compose version : 1.23.2, build 1110ad01

do you requires any other information?

**Comment by clint-tseng** [comment]
at this point, i think i just have to wait for somebody else to exhibit this problem, and then we can see what the commonalities are. as-is, i'm not knowledgeable enough about `apt` to debug this issue remotely. sorry. we'll leave this ticket open and see if anybody else sees the same thing.

**Comment by clint-tseng** [comment]
hey @arkhub if you go back to the base `service.dockerfile` and just change `node:carbon` to `node:8.11.3` does that work?

**Comment by arkhub** [comment]
Do I have to run docker-compose create after that?

**Comment by clint-tseng** [comment]
yeah, you would.

**Comment by clint-tseng** [comment]
okay! turns out to be some sort of weird package pinning incompatibility with the latest `node:carbon` versions.. #45 should have resolved it on master.
