### ISSUE TITLE
Failed to get image in server after successful form submission

### ISSUE THREAD

**Issue by arkhub** [opendatakit/central#38]
Tried some test form with geopoints and image, all seems works well (create user, upload form, get blank form, upload submissions) until I try to retrieve images in submitted form which shown error `{"message":"Could not find the resource you were looking for.","code":404.1}` .
Downloading the form also only get the xls file in zip format, but no images present, is there any step in installing or configuring the server that I miss?

**Comment by arkhub** [comment]
I've tried to download it from the web ui in the submissions list using chrome browser, viewing it cause the 404 code like above.

Downloading the zip only result in the xlsx files only after being extracted. I'll try to look the files in the server / docker images next since `docker-compose logs -f` doesn't show anything weird when the being submitted.

**Comment by clint-tseng** [comment]
oh, i see. so you are getting that error message when clicking on the link in the table? @matthew-white  any ideas?

**Comment by clint-tseng** [comment]
@arkhub is there any chance i could get access to the server to try it? even just to the web panel?

**Comment by arkhub** [comment]
sure, do you want to access to web panel? I'll create the users first

**Comment by clint-tseng** [comment]
any sort of access would help a lot! my email address should be visible on my github profile.

the leftover data may be helpful, but i just responded on the other thread with information about removing your data.

**Comment by arkhub** [comment]
Ok. this is embarrasing... when I try to upload another pictures it succeded and I managed to download it. turns out previous failed image is in .png format (don't know why it failed because odk collect submitted it normally), and the successful on is in .jpg format.

still, do you want to access the server to test it out? if yes how do I send the user pass information in private message? (didn't find message button in github), or do I email to you directly?

**Comment by clint-tseng** [comment]
oh! that's really interesting. i wonder why a `.png` doesn't work. i think with that information i can do some testing myself, and i probably don't need to access your server. 

but i think odk collect only generates `.jpg`s, so if that's how you are collecting data then this shouldn't be a problem.

**Comment by arkhub** [comment]
ok then.
