### ISSUE TITLE
Video and audio format when attaching from odk collect

### ISSUE THREAD

**Issue by arkhub** [opendatakit/central#47]
I noticed that like previous problem in images (.png not supported for images when previewing or downloading in user interface), the audio also had similar problem when trying to upload .mp3 format (as example). Is there any limitation on what extension for audio and video format? thank you.

**Comment by clint-tseng** [comment]
it shouldn't care at all .. as far as central is concerned it's all just a pile of bytes. it doesn't do any special processing of any filetypes, nor does it expect any particular filetype.

**Comment by clint-tseng** [comment]
hey @arkhub, did you ever figure out what was going on here? is the problem still occurring?

**Comment by clint-tseng** [comment]
after investigation, this is likely the same problem as the file-upload-widget issue linked above.

**Comment by clint-tseng** [comment]
Closing in favor of https://github.com/opendatakit/collect/pull/3038

**Comment by arkhub** [comment]
> hey @arkhub, did you ever figure out what was going on here? is the problem still occurring?

Sorry for the late reply, no I haven't figure it out why, so in the meantime I just have to tell anyone who try to submit form to upload only compatible extension like .jpeg etc.

**Comment by clint-tseng** [comment]
okay. we think we've found the issue; an upcoming Collect update should resolve the problem. thanks for the report!
