### ISSUE TITLE
Unable to start SystemD

### ISSUE THREAD

**Issue by arkhub** [opendatakit/central#55]
I've tried following the readme given, by copying the systemctl files using ```cp files/docker-compose@.service /etc/systemd/system``` and when I try to run
```systemctl start docker-compose@central``` it says : (using non root user)
```
Failed to get D-Bus connection: No such file or directory
```
when I try using sudo, there's no error but when I check the status it said :
```
● docker-compose@central.service - central via docker-compose
   Loaded: loaded (/etc/systemd/system/docker-compose@.service; disabled)
   Active: failed (Result: start-limit) since Sun 2019-02-17 16:57:44 WIB; 3s ago
  Process: 4456 ExecStop=/usr/local/bin/docker-compose stop -v (code=exited, status=200/CHDIR)
  Process: 4455 ExecStart=/usr/local/bin/docker-compose up (code=exited, status=200/CHDIR)
 Main PID: 4455 (code=exited, status=200/CHDIR)

Feb 17 16:57:43 <my domain name> systemd[1]: docker-compose@central.service: control process exited, code=exited status=200
Feb 17 16:57:43 <my domain name> systemd[1]: Unit docker-compose@central.service entered failed state.
Feb 17 16:57:44 <my domain name> systemd[1]: docker-compose@central.service holdoff time over, scheduling restart.
Feb 17 16:57:44 <my domain name> systemd[1]: Stopping central via docker-compose...
Feb 17 16:57:44 <my domain name> systemd[1]: Starting central via docker-compose...
Feb 17 16:57:44 <my domain name> systemd[1]: docker-compose@central.service start request repeated too quickly, refusing to start.
Feb 17 16:57:44 <my domain name> systemd[1]: Failed to start central via docker-compose.
Feb 17 16:57:44 <my domain name> systemd[1]: Unit docker-compose@central.service entered failed state.
```

**Comment by arkhub** [comment]
Update : turns out the ```workingdir``` variable in ```docker-compose@.service``` is the culprit, I have the "central" directory not in root folder (run as non root user with elevated sudo), so i have to change the ```workingdir``` from ```/root/%i``` to ```/home/<myuser>/%i```.

Still I somewhat think this is not a "recommended" solution for workingdir, just a temporary fix for my case.

**Comment by clint-tseng** [comment]
oh, i see. yeah, the instructions and everything are sort of one packaged unit; if you deviate from them i cannot guarantee that they'll all work without some individual attention.
