### ISSUE TITLE
0.4.0-beta.1 is cant see app user

### ISSUE THREAD

**Issue by kokoye2007** [opendatakit/central#58]
I upgrade 0.4.0 and its can't run, bug is fix on 0.4.0-beta.1
but can't find app user create setting.

**Comment by kokoye2007** [comment]
Sorry 
Project Create and Add App User.

**Comment by clint-tseng** [comment]
no problem! if you have any more problems, please don't hesitate to ask on [the forum](https://forum.opendatakit.org/t/odk-central-v0-4-beta/16857/2)!
