### ISSUE TITLE
Context on the README document

### ISSUE THREAD

**Issue by nribeka** [opendatakit/central#62]
When folks are coming directly to this repository, they won't be able to get a context of what's going on in this repo. I think it will be beneficial to pull some information from the docs repo and put it here to give some information and context of what's, what are the plan and the trajectory.

**Comment by clint-tseng** [comment]
agreed! now that 0.4 is released, we can get rid of a lot of the technical documentation and replace it with other material; this was the plan/idea behind moving the deployment information to the odk docs website. i will do that soon. thanks for the feedback!
