### ISSUE TITLE
docker-compose up not working because of Debian Jessie removal

### ISSUE THREAD

**Issue by adamvert** [opendatakit/central#64]
A few days ago, Debian announced the removal of non-LTS Jessie from their mirrors:

https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

This now causes problems for namshi/smtp, which is trying to access jessie-updates. I realise that this is an upstream issue that should probably be fixed on namshi/smtp, and I've opened an issue there (https://github.com/namshi/docker-smtp/issues/50), but it might be worth trying to figure out a workaround?

**Comment by clint-tseng** [comment]
well, this explains what @ggalmazor saw. i'm not sure how to work around this—let's see what they say upstream.

**Comment by hyances** [comment]
Hey! Looks that there is a solution for this https://github.com/namshi/docker-smtp/pull/51

**Comment by yanokwa** [comment]
Fixed by https://github.com/namshi/docker-smtp/pull/51

**Comment by hyances** [comment]
So, it is just to clone central again and do `$ git submodule update -i`?  Thanks for your guide.

**Comment by yanokwa** [comment]
@hyances It's upstream, so all you should have to do is the `docker-compose build`.

**Comment by clint-tseng** [comment]
that's not entirely true.. your machine has a base copy of `namshi/smtp` sitting around that it thinks is totally up-to-date and it doesn't realize there is a fixed image available.

you may have to run `docker rmi namshi/smtp` before running `docker-compose build`.

**Comment by clint-tseng** [comment]
oh, it's possible you could alternatively run `docker pull namshi/smtp`, but i'm not completely sure.
