### ISSUE TITLE
Repeated subgroups in OData?

### ISSUE THREAD

**Issue by florianm** [opendatakit/central#74]
Is there any way of accessing the data of repeated groups through the OData feed? 

I can see the main form under /Submissions, but so far I couldn't discover any link to groups in both the metadata or the form data. 

Any pointers would be greatly appreciated!

**Comment by florianm** [comment]
Found it: Metadata > DataServices > Schema > two EntityType, one with attribute "Submissions", one with "Submissions.taxon_encounter" - those work as postfixes for the .svc URL.

**Comment by issa-tseng** [comment]
yup! the odata metadata document serves as a kind of local service directory:

https://odkcentral.docs.apiary.io/#reference/odata-endpoints/odata-form-service/service-document

**Comment by florianm** [comment]
Thanks - got it to work: https://dbca-wa.github.io/ruODK/articles/example.html

One suggestion: link that fantastic apiary.io site prominently in Central's OData popup - I got stuck in proprietary Excel/PowerBI tarpits before I discovered apiary through the ODK docs.

**Comment by issa-tseng** [comment]
filed!
