### ISSUE TITLE
Initial startup not completing

### ISSUE THREAD

**Issue by smoyth** [opendatakit/central#83]
I tried following the instructions and got as far as `docker-compose up` but it's failing at this step:

```
nginx_1     | writing a new nginx configuration file..
nginx_1     | 2019/07/31 19:57:29 [emerg] 40#40: BIO_new_file("/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1     | nginx: [emerg] BIO_new_file("/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
central_nginx_1 exited with code 1
```

Tried closing and running again. Then it gets as far as the below and hangs:

```
nginx_1     | writing a new nginx configuration file..
nginx_1     | 2019/07/31 20:02:18 [emerg] 8#8: BIO_new_file("/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1     | nginx: [emerg] BIO_new_file("/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/selfsign|letsencrypt|customssl/live/local|your.domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
central_nginx_1 exited with code 1
service_1   | running migrations..
service_1   | starting cron..
service_1   | starting server.
```

Am I doing something wrong?

**Comment by issa-tseng** [comment]
hello @smoyth:

first, please direct support questions onto the [support forum](https://forum.opendatakit.org/c/support) so that others may help and learn.

second, it looks like you haven't correctly set up your settings file. please take a look in the instructions where it says "Next, you need to update some settings." and ensure that you have performed those steps.

if that doesn't do it, please ask your follow-up questions on the forum.

**Comment by smoyth** [comment]
I'm trying to set up a dev build on my local machine. I don't see "Next, you need to update some settings." anywhere in the README file. That's why I filed an issue—it seems like your dev env setup instructions are incomplete. Sorry for not being more specific, and thanks for the quick response!

**Comment by issa-tseng** [comment]
yes, the dev instructions are not meant to be comprehensive. please see the full documentation here:

https://docs.opendatakit.org/central-install-digital-ocean/

you need to change the vars in your .env file.

**Comment by lognaturel** [comment]
@issa-tseng, it should probably be possible to follow the dev instructions exactly and get something working. If that's not the case, probably they should link out to that docs page directly?

**Comment by issa-tseng** [comment]
i think perhaps i should just delete the dev instructions altogether. people probably shouldn’t be installing things this way.

**Comment by lognaturel** [comment]
That sounds great.
