### ISSUE TITLE
ODK Central 0.7 release

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central#86]
This release covers a number of improvements to existing functionality:

* Rework the Form State workflow and consolidate them up to the Project level.
* Allow granular visibility control per App User.
* Appoint read-only Viewers on a Project.
* Basic consolidation of timing audit logs during export.
* Other smaller fixes.

Preliminary release criteria and story status may be found [here](https://docs.google.com/document/d/1aom9LlL7ClDUhncHcW-3_GB_PczbB-spvrg9zIJn5qQ).

Comments and feedback may be left directly on the document, or here in this ticket.

**Comment by michaeledwardmarks** [comment]
Will read-only viewers have ability to download data?
I presume so or would want that as a level of granularity

**Comment by issa-tseng** [comment]
yes!

**Comment by florianm** [comment]
Asking for ruODK: What's the best way to estimate the timeline of new ODK Central releases? I'm trying to keep ruODK up to date against the current release.

**Comment by issa-tseng** [comment]
unfortunately we don’t plan firm dates in advance because our team is so incredibly small: life things and small misestimations have a huge impact on our schedule, along with external pressures like support and maintenance. but if you check in with at the document linked on this ticket, we update it continually with our current status and you can tell we are close to release when it starts looking like mostly checkmarks. we also discuss the release status on the developer’s slack (for anybody else reading, please only use this resource if you are contributing to odk development).

in addition, i’m happy to drop you a note when we are close each time. we try not to release breaking changes, of course, but i appreciate that you try to keep up with new things as we get them out.

**Comment by florianm** [comment]
That's perfectly fine, thanks! My only goal is to keep up with ODK Central. ruODK unit tests run against the Central sandbox so I notice anything breaking quickly enough.
