### ISSUE TITLE
Ensure master always builds cleanly

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/central#88]
It'd be nice to run docker-compose on master to ensure the build works. 

Issa sez:
> if that is possible then yes. first we should have some process so master stays clean
> 
> i would have a release branch or something but i feel like it adds a step people could get wrong when cloning and people already have clones on master
> 
> so possibly we should merge to a prerelease and then merge that to master. though i have also had headaches in the past with long-running staging branches accumulating unintended deltas against master due to merge conflicts
> 
> https://circleci.com/docs/2.0/docker-compose/ looks like the CI thing may be possible

**Comment by yanokwa** [comment]
For what it's worth, I like having just the master branch. And this problem isn't super common, so I'd be OK with using CI to make sure it builds and leaving it at that. We could also update the docs to and tell people to checkout a particular tag.

**Comment by issa-tseng** [comment]
yeah the main thing here for me isn't as much the CI (though i will do that too) but some kind of documented process for managing a release and what merges to `master` when. i should have realized that i couldn't merge that change but i didn't.
