### ISSUE TITLE
Add description to projects and forms

### ISSUE THREAD

**Issue by florianm** [opendatakit/central#94]
Non-urgent feature suggestion: a plain text (or markdown) field "description" for projects and forms to let admins add a short but friendly description for users.

Detail views could show description next to project/form title (positioning see "let's get some things done" catchphrase).
List views could show description as a column after title.
Update could happen in respective project/form settings tab.

**Comment by issa-tseng** [comment]
hey florian!

in general, we prefer feature requests to go [on the forum](https://forum.opendatakit.org/c/features) so more people can participate in them.

in the case of this one, it's been planned! i'll try to work it in soon. thanks for the feedback. :)

**Comment by florianm** [comment]
Sweet, thanks! Will post to forum next time ;-)

re [story 5.33](https://docs.google.com/spreadsheets/d/1VqCa4__FiSifO8G35koZHZtMhmaIsJ-eJQxGv_RAHm0/edit#gid=0&range=D107), working on submission to ROpenSci (process at  https://github.com/ropensci/software-review/issues/335) hoping to get adopted before mid October.

**Comment by issa-tseng** [comment]
:) neat!

**Comment by florianm** [comment]
Now that we're running prod and UAT sites for ODK Central, setting the colour and title of the navbar would be a useful visual cue. Currently I have to squint at the URL to see whether I'm in prod or UAT.
