### ISSUE TITLE
Support SSL between backend, db, frontent

### ISSUE THREAD

**Issue by florianm** [opendatakit/central#96]
I've set up a fresh instance of ODK Central as K8s pods with a blank postgres11 db. The db apparently requires SSL.

I'm getting this error:
```
root@service-d47b965cd-d4td4:/usr/odk# odk-cmd --email florian.xxx@xxx user-create
prompt: password: xxx

Error: The server does not support SSL connections
    at Socket.<anonymous> (/usr/odk/node_modules/pg/lib/connection.js:86:33)
    at Object.onceWrapper (events.js:291:20)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)Problem [Error]: An unknown internal problem has occurred. Please try again later.
    at Object.unknown (/usr/odk/lib/util/problem.js:39:3)
    at postgresErrorToProblem (/usr/odk/lib/util/db.js:282:34)
    at tryCatcher (/usr/odk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/odk/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/odk/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/odk/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/odk/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/odk/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/odk/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/odk/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/odk/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21) {
  problemCode: 500.1,
  problemDetails: {
    error: Error: The server does not support SSL connections
        at Socket.<anonymous> (/usr/odk/node_modules/pg/lib/connection.js:86:33)
        at Object.onceWrapper (events.js:291:20)
        at Socket.emit (events.js:203:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
  }
}
```

Is that SSL option something the backend could easily support? Not wanting to pile on unnecessary work, but probably required for moving postgres versions forward.

**Comment by issa-tseng** [comment]
are you sure you aren't attempting to connect to a non-SSL database with an SSL connect string?

given the PG client is complaining that "the server does not support SSL connections" i would assume that this means it's trying to connect with SSL to postgres but postgres isn't liking it.

**Comment by florianm** [comment]
The db is a plain postgres:9.6 running in the same cluster/project, no SSL anywhere in the config. The service container also has no SSL config. The only difference to my other, working, ODK Central instance is a slightly newer Docker image (both 0.6 though) and a different k8s cluster (only our infra folks could tell).

I did try connecting to a separately hosted (way gruntier) pg cluster with SSL, setting an env var 'SSLMODEREQUIRE=true' (IIRC), also no joy.

I guess since the images work fine in the docker-compose version, the error must be some kind of wrong config on my end. Complication: all config I can see/edit is exactly identical between working and non-working.

**Comment by issa-tseng** [comment]
okay let's step back.

clarification question:
is it that you're running into this error for whatever reason and therefore your ask is SSL so the error goes away, or
is it that you're trying to set up SSL between all these components and that's why you're getting this error?

**Comment by florianm** [comment]
Context needed ;-)

what I'm doing:
* Trying to run self-hosted ODK Central
* Must run on our own infra - flavour of the month is Azure, K8s, Rancher. Own nginx proxy/reverse proxy and firewall. Own SSL certs (for reverse proxied name) and mail server.
* Expected data volume exceeds local pod allocation, would like to use our hosted pg cluster (has ample storage), but that's pg11 with SSL required.
* Running as close to vanilla ODK Central docker-compose as possible, even using local postgres pod.
* Setup described [here](https://forum.opendatakit.org/t/installing-odk-central-in-microsoft-azure-cloud/18020/2).

Current problem narrowed down to:
```
frontend talks to localhost:8383:

https://github.com/opendatakit/central-frontend/blob/43a7ed499dc1690253e7b47501ed159dd0c333a2/nginx.conf

# backend allows me to create a web user on odk-cmd
# trying to login through frontend
2019/09/27 05:06:42 [error] 11#11: *28 connect() failed (113: No route to host) while connecting to upstream, client: 172.30.20.40, server: , request: "POST /v1/sessions HTTP/1.1", upstream: "http://10.244.3.80:8383/v1/sessions", host: "odkcentral-migrated.dbca.wa.gov.au", referrer: "https://odkcentral-migrated.dbca.wa.gov.au/"
172.30.20.40 - - [27/Sep/2019:05:06:42 +0000] "POST /v1/sessions HTTP/1.1" 502 166 "https://odkcentral-migrated.dbca.wa.gov.au/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
```

So the nginx container can't find a route to the service container, although they run side by side (same namespace).
Apologies if this problem strays from the original "but the db wants SSLMODE".

Has anything changed in the last two months in how the frontend finds a route to the backend?

**Comment by issa-tseng** [comment]
from my reading of the error message the central-backend service is _already_ trying to use SSL to connect to the database, and the database is the one that doesn't allow that.

`Error: The server does not support SSL connections` - remember that from the context of `libpg`, it is the _client_ and the _database_ is the server.

as for the route to backend stuff, i'm not sure. sounds like a transient issue in your networking. we didn't change anything there. in this case, remember that the "frontend" is just your web browser. it's nginx that's seeking the backend in those logs. if it thinks there is no route, then there is a hostfile issue, or a gateway issue, or something else networky. is `10.244.3.80` local to the nginx host? next time this happens, log into nginx and trace that route and you may get some clues.

**Comment by issa-tseng** [comment]
(i do see that you've done some investigation on this line of thinking, but i'm still pretty sure the problem is more in that direction.)

**Comment by issa-tseng** [comment]
i dug up the source of the error message and indeed it occurs as a result of a _response_ from the database that it does not like SSL:

https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L88

**Comment by florianm** [comment]
> (i do see that you've done some investigation on this line of thinking, but i'm still pretty sure the problem is more in that direction.)

The "route to host" problem was solved by building and restarting the two images.

Thanks for the SSL/pg client tip, chasing up with IT now.

**Comment by matthew-white** [comment]
I think I saw a comment that mentioned the `nginx.conf` in `central-frontend`, so I also wanted to note that that file is mostly intended for local development. The `nginx.conf` in `central-frontend` doesn't do everything that the configuration in the `central` repo does; for example, it doesn't support request-body gzip decompression. This doesn't sound like the source of the issue here, but in case you weren't already, I wanted to recommend that you use the NGINX configuration in the `central` repo as the basis of your work.

**Comment by florianm** [comment]
@issa-tseng @matthew-white retrying while still jet lagged:

* Rebuilt ODK Central images front & backend from latest master.
* Configured our hosted db (server name, un, pw, db name) in local.json.
* Our db *requires* SSL.

Getting this error:

```
wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: timeout occurred after waiting 15 seconds for postgres:5432
running migrations..

Unhandled rejection error: SSL connection is required. Please specify SSL options and retry.

at Connection.parseE (/usr/odk/node_modules/pg/lib/connection.js:545:11)
at Connection.parseMessage (/usr/odk/node_modules/pg/lib/connection.js:370:19)
at Socket.<anonymous> (/usr/odk/node_modules/pg/lib/connection.js:113:22)
at Socket.emit (events.js:203:13)
at addChunk (_stream_readable.js:294:12)
at readableAddChunk (_stream_readable.js:275:11)
at Socket.Readable.push (_stream_readable.js:210:10)
at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
starting cron..
starting server.
```

Do I read above error correctly that the db complains that it requires SSL?
How can I tell ODK Central to *use* SSL when accessing the db?

**Comment by issa-tseng** [comment]
okay, so now i think we agree that postgres wants central to use ssl but it is not. this makes more sense.

i think most likely all you need to do is set the correct configuration in `default.database` in `config.json.template`. i don't know exactly that that would be but if you use a connection string instead of an object i think you'll be able to specify whatever the standard ssl-ish connection string would be. or there may be a config key you can add to the existing object to specify ssl/secure. report back if you figure it out!

we use knexjs.org under the covers, but that just uses the nodejs pg client library under _its_ covers.

**Comment by florianm** [comment]
@issa-tseng knowing that you use knex.js and node-postgres helped me to find the docs about SSL mode at https://node-postgres.com/features/ssl.

Config just needed the addition of `"ssl": {"rejectUnauthorized": false}`:

```
 "database": {
      "host": "DBHOST",
      "user": "USERNAME",
      "password": "PASSWORD",
      "database": "DBNAME",
      "ssl": {"rejectUnauthorized": false}
    },
...
```
Thanks for the help Issa!
